import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../styles/globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex min-h-screen">
          <section className="w-[20%] m-0">
            <aside>
              <Navbar />
            </aside>
          </section>

          <section className="w-[80%]">

            <header className="absolute top-0 h-[80px] w-[80%] gap-20 flex align-center justify-center">
            <h2 className="text-center">Collections</h2>
            <button></button>
            </header>

            <article className="max-w-4xl mx-auto my-[30px] bg-white rounded-xl shadow-md overflow-hidden hover:shadow-xl transition-shadow duration-300
            h-[80%]">
              {children}
            </article>
{/* 
            <footer className="row-start-3 flex gap-[24px] flex-wrap items-center justify-center border w-[80%] h-20
                absolute bottom-0">
              <h2>Welcome To the Miniprojects Hub.</h2>
            </footer> */}
          </section>

        </main>   
      </body>
    </html>
  );
}
